name: TEST

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check Chrome
        run: |
          google-chrome --version
          chromedriver --version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start application
        run: |
          flask db upgrade
          flask init-db
          nohup flask run &

      - name: Run Pytest
        run: pytest

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: htmlcov/
