name: TEST

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/
        sudo rm -f /usr/bin/google-chrome
        sudo ln -s /usr/lib/chromium-browser/chromium-browser /usr/bin/google-chrome
        
    - name: Verify chromium installation
      run: |
        which chromium-browser
        chromium-browser --version 
        
    - name: Run Pytest
      run: pytest
